-- Migration: Add Performance Metrics to ML Ads
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS impressions INTEGER DEFAULT 0;
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0;
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS cost DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS ad_sales DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS acos DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE public.ml_ads ADD COLUMN IF NOT EXISTS ctr DECIMAL(10, 5) DEFAULT 0;
